### ISSUE TITLE
[POSSÍVEL BUG] O PSO ainda não está guardando o melhor individuo de maneira correta

### ISSUE THREAD

**Issue by GuilhermeAGouveia** [GuilhermeAGouveia/heuristic-scientific-research#10]
Veja os resultados de duas execuções da implementação do PSO atual:

![image](https://user-images.githubusercontent.com/81968354/233396024-8debc07b-738c-42b4-bfa9-bb648155ce86.png)

Quando executei o código com 800 gerações o resultado foi melhor do que quando executei com 900 gerações, visto que estou com a semente fixa (como mostra na figura abaixo) isso não deveria acontecer

![image](https://user-images.githubusercontent.com/81968354/233397114-47af5fb9-674f-427d-a800-711d5be79979.png)

**Comment by ViniciusBastoss** [comment]
Não é um bug.Isso ocorre porque da maneira que estamos calculando o w o resultado final será diferente, pois o calculo do w depende do numero de gerações.

![bug best individuo](https://user-images.githubusercontent.com/117671262/233415832-4b969624-4b3f-484a-94f4-07ce29b336ff.png)
