### ISSUE TITLE
Verificar se o uso da seleção do genetico no diferencial realmente melhora ele muito

### ISSUE THREAD

**Issue by GuilhermeAGouveia** [GuilhermeAGouveia/heuristic-scientific-research#35]
![Image](https://github.com/GuilhermeAGouveia/heuristic-scientific-research/assets/81968354/91701c4a-21ef-4807-8a7a-d08d5eb32b16)

### explicacao

A função comentada era seleção do algoritmo diferencial, a outra é do genético que coloquei no diferencial e pareceu melhorar muito

**Comment by GuilhermeAGouveia** [comment]
Usando na função 3 parece que melhorou muito, tem que verificar isso nas outras funções e anotar. Se realmente melhorar muito a gente leva essa discussão para o @iagoac

**Comment by GuilhermeAGouveia** [comment]
Executa com esse comando: `./evol -t 5 -s 1 -f N` 

Daí faz isso pra umas 7 ou mais funções variando o N, o -s é pra fixar semente e garantir que as populações iniciais aleatórios sejam as mesmas, o -t é pra não vc não gastar muito tempo esperando, afinal é só um teste rápido

**Comment by ViniciusBastoss** [comment]
![select genetico vs diferencial](https://github.com/GuilhermeAGouveia/heuristic-scientific-research/assets/117671262/683c7126-db04-4d54-a224-808a8bfd2017)
Foi realizada a otimização de parâmetros utilizando as duas variações da função de seleção. Os resultados na imagem foram obtidos através do comando ./evol -t 5 -s 1 -f N, onde 8 funções obtiveram um resultado melhor utilizando a seleção do diferencial contra 7 da seleção do genético. Além disso o script furaaf.sh foi executado e 11 funções obtiveram um resultado melhor utilizando a seleção do diferencial contra 4 da seleção do genético levando em conta a média final.

**Comment by GuilhermeAGouveia** [comment]
Blz. Com isso fica claro que é melhor manter a seleção original do diferencial.
